### ISSUE TITLE
Switch over to using Maehw's code (and the official Sensirion library).

### ISSUE THREAD

**Issue by RobertLRead** [PubInv/ventmon-ventilator-inline-test-monitor#11]
@maehw has pointed out that they have a more complete use so Sensirion code.  The project will be far more robust when I have used their code:

https://github.com/maehw/diy-beatmungsgeraet/tree/master/software/mass-airflow-sensor/controller-software

**Comment by maehw** [comment]
Hi @RobertLRead: our code is not based on Sensirion code.

When I did some research back then I found the following repositories:

- https://github.com/Sensirion/libsensors-python (deprecated)
- https://github.com/Sensirion/arduino-liquid-flow-snippets
- https://github.com/Sensirion/arduino-sdp

IIRC they cover sensors, but not meters as the SFM3xxx.
