### ISSUE TITLE
Manual Formatting

### ISSUE THREAD

**Issue by lauriaclarke** [PubInv/ventmon-ventilator-inline-test-monitor#12]
For some reason the normal GitHub header and footer are to the side of the user manual when viewing the page, making it hard to read. Not sure how to fix this. See attached photo.
![github](https://user-images.githubusercontent.com/8439287/81061440-5af3e180-8ea2-11ea-9861-af7fa0438042.png)

**Comment by RobertLRead** [comment]
I can't duplicate in Chrome --- what browser are you using?
