### ISSUE TITLE
Feature Request - Second SFM3/4xxx for monitoring input air/O2 injection  (pneumatics)

### ISSUE THREAD

**Issue by armeetrooper** [PubInv/ventmon-ventilator-inline-test-monitor#18]
Hey guys

First off thank you for the amazing work. 

One issue unique to ARMEE is the pneumatic power source. We would like to somehow integrate a second flow meter to monitor incoming air supply conditions. 

Is this something that can be 
- electrically implemented
- programmed to display a baseline input/o2 flow rate. 

Thanks in advance and keep up the great work!

**Comment by RobertLRead** [comment]
I'm closing this issue.  It's a good idea but our basic approach to this would be to use to VentMons. We have now implemented timing in the datastream that should (in theory) make anything you wanted to do in this way possible.
