### ISSUE TITLE
A test lung reference data set?

### ISSUE THREAD

**Issue by synergiator** [PubInv/ventmon-ventilator-inline-test-monitor#4]
Dear test team,

is there a reference data set describing the tests with the test lung?

https://gitlab.com/open-source-ventilator/OpenLung/-/issues/133

There is [breath_data](https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/breath_data/rob_even.json) folder with a json file and a Python data server in this project - is that what we are looking for?

**Comment by RobertLRead** [comment]
This is a great question; possibly a new repo should be created to create a breath data set.  However, first we would have to have a standard for how the data should be represented.  I have a simple approach that I am using, but was not ready to propose it as a standard.  You can see it [here](https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/breath_data/rob_even.json). That is me breathing evenly into an OPEN tube (not a test lung, which will round off the corners. We really need a standard and about 10 test files.  I now have the ability to add that; I will attempt to add some more data today.  We might be able to find better data examples, but I know of none.  BTW, this proejct has Flow data; most projects probably don't, they will have pressure data, which is quite different. Ideally, we would have a standard that allows BOTH to be treated together, (and supports one being missing.)

**Comment by RobertLRead** [comment]
I've added a new data file that contains pressures, and is at a higher sampling rate. This is of me breathing into a plastic test lung that provides considerable resistance. I'm using the 5cmH20 adapter when plugging into the test lung. This format is still awful. I will try to produce a good standard unless you guys get to it first, or find one on the web: [https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/breath_data/rob_test_lung_breath_even.json](https://github.com/PubInv/ventmon-ventilator-inline-test-monitor/blob/master/breath_data/rob_test_lung_breath_even.json)
