### ISSUE TITLE
Flow Sensor alternates due to supply-chain crunch,

### ISSUE THREAD

**Issue by EnginerdingDan** [PubInv/ventmon-ventilator-inline-test-monitor#8]
The FM3200 is a really fantastic sensor from a specifications point of view.

The cons for the developing world, I think will be: price (it's $170/ea).
And perhaps even bigger, availability.  I just checked Octopart and less than 100 in the world in-stock for the AW and AG models.

Erg, I propose one of the priorities-of-work would be finding a suitable alternative.

Automotive Mass Air Flow Sensor?  They seem to be very cheap, have *similar* input/output dimensions, are probably available in qty in the developing world.  I do not however, know if the engineering specifications would match. 

![AutomotiveMassAirSensors](https://user-images.githubusercontent.com/62954183/78157526-0e823580-740e-11ea-9654-f0a7dceff3f4.png)

**Comment by RobertLRead** [comment]
I think this is an important point.  I haven't really been thinking about it yet, but having the system modular so you can use essentially the same system with multiple flow meters is a good idea. It would really help if those were standard 22mm airway meters.  If not, we might have to build a male port on  side, a female on the other, and then change the interior design based on which flow meter you use.

**Comment by EnginerdingDan** [comment]
I ordered some low-cost automotive oxygen and MAF sensors that should be accessible to the developing world in terms of price.  Next week, I should have a universal guide up.  I don't know if the engineering specifications will be suitable, particularly the flow sensor (it has a much higher rate of flow, I'm assuming), but will keep searching for some typical specs for small cars.

I'm assuming the smaller the vehicle the mass air flow sensor comes from, the better from an engineering spec point of view.  ATV's and bikes might be the trick, but I think may be quite a bit more expensive. 

![Annotation 2020-04-02 205459](https://user-images.githubusercontent.com/62954183/78313470-d0c40080-7524-11ea-86ce-070241baa077.png)
![Annotation 2020-04-02 205601](https://user-images.githubusercontent.com/62954183/78313472-d15c9700-7524-11ea-906f-62431389f78c.png)

**Comment by RobertLRead** [comment]
Did you ever publish that guide? I would like to link to it on the main site, but I have to have a URL to link to.
